In [1]:
import pandas as pd
import matplotlib as mplt
import numpy as np

In [2]:
pip install openpyxl #forsavingexcelfile

Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)

# **Key Points**

- **Understand the data** (column names, datatypes, no of rows ) ,
- **Clean the dataset** ( Remove duplicates, missing values, Fix inconsistent formatting (e.g. date formats, capitalization) ,Remove unnecessary columns ),
- **Standardize Column Names** (Common columns (like ID, date, etc.) match in both datasets ,No typos or spacing issues )
- **Merge or Join Datasets** (Use merge() in pandas (or JOIN in SQL) to combine the datasets based on common keys (like user_id, order_id, etc.) )
- **Feature Engineering** ( Create new columns from existing ones (e.g. year, day, total_price) ,Convert dates to datetime type )
- **Check for Outliers and Consistency** ( Use describe() and visualizations (boxplot, histograms) to identify outliers )
- **Save the Cleaned Data** ( df_merged.to_csv("cleaned_dataset.csv", index=False)
 )

**We have two dataset 2023 & 2024**

In [28]:
df1 = pd.read_excel("Bookings2023.xlsx")
df2 = pd.read_excel("Bookings-2024.xlsx")

**Checking dataset info**

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              0 non-null       float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(12)
memory usage: 15.7+ MB

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20407 entries, 0 to 20406
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        20407 non-null  datetime64[ns]
 1   Time                        20407 non-null  object
 2   Booking_ID                  20407 non-null  object
 3   Booking_Status              20407 non-null  object
 4   Customer_ID                 20407 non-null  object
 5   Vehicle_Type                20407 non-null  object
 6   Pickup_Location             20407 non-null  object
 7   Drop_Location               20407 non-null  object
 8   V_TAT                       12652 non-null  float64
 9   C_TAT                       12652 non-null  float64
 10  Canceled_Rides_by_Customer  2081 non-null   object
 11  Canceled_Rides_by_Driver    3654 non-null   object
 12  Incomplete_Rides            12652 non-null  object
 13  Incomplete_Rides_Reason     795 non-null    object
 14  Booking_Value               20407 non-null  int64
 15  Payment_Method              12652 non-null  object
 16  Ride_Distance               20407 non-null  int64
 17  Driver_Ratings              12652 non-null  float64
 18  Customer_Rating             12652 non-null  float64
 19  Vehicle Images              0 non-null      float64
dtypes: datetime64[ns](1), float64(5), int64(2), object(12)
memory usage: 3.1+ MB

In [ ]:
df1.head(100)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-07-01 05:03:00,05:03:00,CNR4158584922,Success,CID772392,Auto,Sahakar Nagar,Ramamurthy Nagar,35.0,45.0,NaN,NaN,No,NaN,934,UPI,12,3.3,5.0,NaN
96,2024-07-23 04:01:00,04:01:00,CNR5133236273,Canceled by Driver,CID905849,Prime Plus,Banashankari,Chickpet,NaN,NaN,NaN,Customer related issue,NaN,NaN,615,NaN,0,NaN,NaN,NaN
97,2024-07-26 08:22:00,08:22:00,CNR5661490576,Success,CID546076,Bike,Magadi Road,Electronic City,56.0,30.0,NaN,NaN,No,NaN,2202,Cash,44,4.7,3.4,NaN
98,2024-07-05 12:36:00,12:36:00,CNR2304446757,Success,CID432144,eBike,Rajarajeshwari Nagar,MG Road,252.0,145.0,NaN,NaN,No,NaN,205,Cash,43,4.1,3.1,NaN
99,2024-07-18 07:21:00,07:21:00,CNR3780555542,Canceled by Customer,CID803813,Mini,Tumkur Road,Chamarajpet,NaN,NaN,Driver asked to cancel,NaN,NaN,NaN,513,NaN,0,NaN,NaN,NaN

In [ ]:
df2.head(100)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-07-01 05:03:00,05:03:00,CNR4158584922,Success,CID772392,Auto,Sahakar Nagar,Ramamurthy Nagar,35.0,45.0,NaN,NaN,No,NaN,934,UPI,12,3.3,5.0,NaN
96,2024-07-23 04:01:00,04:01:00,CNR5133236273,Canceled by Driver,CID905849,Prime Plus,Banashankari,Chickpet,NaN,NaN,NaN,Customer related issue,NaN,NaN,615,NaN,0,NaN,NaN,NaN
97,2024-07-26 08:22:00,08:22:00,CNR5661490576,Success,CID546076,Bike,Magadi Road,Electronic City,56.0,30.0,NaN,NaN,No,NaN,2202,Cash,44,4.7,3.4,NaN
98,2024-07-05 12:36:00,12:36:00,CNR2304446757,Success,CID432144,eBike,Rajarajeshwari Nagar,MG Road,252.0,145.0,NaN,NaN,No,NaN,205,Cash,43,4.1,3.1,NaN
99,2024-07-18 07:21:00,07:21:00,CNR3780555542,Canceled by Customer,CID803813,Mini,Tumkur Road,Chamarajpet,NaN,NaN,Driver asked to cancel,NaN,NaN,NaN,513,NaN,0,NaN,NaN,NaN

In [ ]:
df2.shape

(20407, 20)

In [ ]:
df1.shape

(103024, 20)

**Merge datasets df1 & df2**
- ( using concat function because we have same columns in both dataset ,Row-wise stacking : Adding more records one below the other)

In [29]:
final_df = pd.concat([df1 , df2 ] , axis=0) #row wise concat add another dataset below another

In [ ]:
final_df.shape

(123431, 20)

In [ ]:
final_df.head(100)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,NaN
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,NaN
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,NaN
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,NaN
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-07-01 05:03:00,05:03:00,CNR4158584922,Success,CID772392,Auto,Sahakar Nagar,Ramamurthy Nagar,35.0,45.0,NaN,NaN,No,NaN,934,UPI,12,3.3,5.0,NaN
96,2024-07-23 04:01:00,04:01:00,CNR5133236273,Canceled by Driver,CID905849,Prime Plus,Banashankari,Chickpet,NaN,NaN,NaN,Customer related issue,NaN,NaN,615,NaN,0,NaN,NaN,NaN
97,2024-07-26 08:22:00,08:22:00,CNR5661490576,Success,CID546076,Bike,Magadi Road,Electronic City,56.0,30.0,NaN,NaN,No,NaN,2202,Cash,44,4.7,3.4,NaN
98,2024-07-05 12:36:00,12:36:00,CNR2304446757,Success,CID432144,eBike,Rajarajeshwari Nagar,MG Road,252.0,145.0,NaN,NaN,No,NaN,205,Cash,43,4.1,3.1,NaN
99,2024-07-18 07:21:00,07:21:00,CNR3780555542,Canceled by Customer,CID803813,Mini,Tumkur Road,Chamarajpet,NaN,NaN,Driver asked to cancel,NaN,NaN,NaN,513,NaN,0,NaN,NaN,NaN

**Clean the dataset first**

 - Do this before changing datatypes.
   Why?
 - Missing or invalid values can prevent proper type conversion.
 - Example: If a column has empty strings or "N/A", converting it to
   datetime or numeric will fail

Dealing with missing values

In [ ]:
final_df.isnull().sum()

Date                               0
Time                               0
Booking_ID                         0
Booking_Status                     0
Customer_ID                        0
Vehicle_Type                       0
Pickup_Location                    0
Drop_Location                      0
V_TAT                          46812
C_TAT                          46812
Canceled_Rides_by_Customer    110851
Canceled_Rides_by_Driver      101343
Incomplete_Rides               46812
Incomplete_Rides_Reason       118710
Booking_Value                      0
Payment_Method                 46812
Ride_Distance                      0
Driver_Ratings                 46812
Customer_Rating                46812
Vehicle Images                123431
dtype: int64

Canceled_Rides_by_Customer , Canceled_Rides_by_Driver , Incomplete_Rides_Reason , Vehicle Images ( all  this columns have 1Lakh+ missing value specially Vehicle Images all missing value )

Drop Vehicle Images Column

In [30]:
final_df.drop("Vehicle Images" , axis = 1 , inplace = True) #axis=1 just to pandas should know we want drop colm not row & inplace = true
                                                                         #means make changes in original dataset directly

In [ ]:
final_df.head(100)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NO,Personal & Car related issue,NAN,NO,444,NO,0,0,0
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NO,NO,No,NO,158,Cash,13,4,4
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NO,NO,No,NO,386,UPI,40,4,4
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NO,NAN,NO,384,NO,0,0,0
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NO,NO,No,NO,822,Credit Card,45,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2024-07-01 05:03:00,05:03:00,CNR4158584922,Success,CID772392,Auto,Sahakar Nagar,Ramamurthy Nagar,35.0,45.0,NO,NO,No,NO,934,UPI,12,3,5
96,2024-07-23 04:01:00,04:01:00,CNR5133236273,Canceled by Driver,CID905849,Prime Plus,Banashankari,Chickpet,0.0,0.0,NO,Customer related issue,NAN,NO,615,NO,0,0,0
97,2024-07-26 08:22:00,08:22:00,CNR5661490576,Success,CID546076,Bike,Magadi Road,Electronic City,56.0,30.0,NO,NO,No,NO,2202,Cash,44,4,3
98,2024-07-05 12:36:00,12:36:00,CNR2304446757,Success,CID432144,eBike,Rajarajeshwari Nagar,MG Road,252.0,145.0,NO,NO,No,NO,205,Cash,43,4,3
99,2024-07-18 07:21:00,07:21:00,CNR3780555542,Canceled by Customer,CID803813,Mini,Tumkur Road,Chamarajpet,0.0,0.0,Driver asked to cancel,NO,NAN,NO,513,NO,0,0,0

In [ ]:
final_df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
V_TAT                         0
C_TAT                         0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
dtype: int64

In [ ]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 123431 entries, 0 to 20406
Data columns (total 19 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        123431 non-null  datetime64[ns]
 1   Time                        123431 non-null  object
 2   Booking_ID                  123431 non-null  object
 3   Booking_Status              123431 non-null  object
 4   Customer_ID                 123431 non-null  object
 5   Vehicle_Type                123431 non-null  object
 6   Pickup_Location             123431 non-null  object
 7   Drop_Location               123431 non-null  object
 8   V_TAT                       123431 non-null  float64
 9   C_TAT                       123431 non-null  float64
 10  Canceled_Rides_by_Customer  123431 non-null  object
 11  Canceled_Rides_by_Driver    123431 non-null  object
 12  Incomplete_Rides            123431 non-null  object
 13  Incomplete_Rides_Reason     123431 non-null  object
 14  Booking_Value               123431 non-null  int64
 15  Payment_Method              123431 non-null  object
 16  Ride_Distance               123431 non-null  int64
 17  Driver_Ratings              123431 non-null  int64
 18  Customer_Rating             123431 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(12)
memory usage: 18.8+ MB

Dealing with null values & we cannot remove duplicate here because data can repeated if one person book ride multiple times

change null values with ("  ") space because if we put 0 then there was some columns which allready have value of 0 inside them , same with 'NO' As well 50/70 % data is null so we cannot remove it direct in that case we can,t get any data there , just need to filtered data when we making dashboard power bi

In [31]:
#REMOVING NULL VALUES COLUMN WISE

final_df["Customer_Rating"].fillna( 00 , inplace=True)
final_df["Driver_Ratings"].fillna(00, inplace=True)
final_df['Payment_Method'].fillna("NO", inplace=True)

final_df["Incomplete_Rides_Reason"].fillna("NO", inplace=True)
final_df["Incomplete_Rides"].fillna( "NAN" , inplace=True)
final_df["Canceled_Rides_by_Driver"].fillna("NO", inplace=True)
final_df['Canceled_Rides_by_Customer'].fillna("NO", inplace=True)
final_df["C_TAT"].fillna(00, inplace=True)
final_df["V_TAT"].fillna(00, inplace=True)

<ipython-input-31-673fd1c8fa7d>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["Customer_Rating"].fillna( 00 , inplace=True)
<ipython-input-31-673fd1c8fa7d>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["Driver_Ratings"].fillna(00, inplace=True)
<ipython-input-31-673fd1c8fa7d>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Payment_Method'].fillna("NO", inplace=True)
<ipython-input-31-673fd1c8fa7d>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["Incomplete_Rides_Reason"].fillna("NO", inplace=True)
<ipython-input-31-673fd1c8fa7d>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["Incomplete_Rides"].fillna( "NAN" , inplace=True)
<ipython-input-31-673fd1c8fa7d>:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["Canceled_Rides_by_Driver"].fillna("NO", inplace=True)
<ipython-input-31-673fd1c8fa7d>:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df['Canceled_Rides_by_Customer'].fillna("NO", inplace=True)
<ipython-input-31-673fd1c8fa7d>:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["C_TAT"].fillna(00, inplace=True)
<ipython-input-31-673fd1c8fa7d>:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_df["V_TAT"].fillna(00, inplace=True)

Change datatypes & indtify problems with column vise

In [32]:
final_df["Customer_Rating"] = final_df["Customer_Rating"].astype(int)
final_df['Driver_Ratings'] = final_df["Driver_Ratings"].astype(int)
final_df["V_TAT"]=final_df["V_TAT"].astype(float)
final_df["C_TAT"]=final_df["C_TAT"].astype(float)

**Check for Outliers and deal with them**
-  Outliers are data points that are significantly higher or lower than most of the other values in a dataset.
 Example: If most people earn ₹30,000–₹70,000, but one person earns ₹5,00,000 — that's an outlier

In [ ]:
# How to Check Outliers in Pandas

#Check if min or max are far from 25%, 50%, or 75%

final_df["Booking_Value"].describe()

count    123431.000000
mean        548.349159
std         536.053666
min         100.000000
25%         242.000000
50%         386.000000
75%         621.000000
max        2999.000000
Name: Booking_Value, dtype: float64

# **What to Do With Outliers (As a Data Analyst)**

-  Situation            &                	Action  
- Data entry mistake	       -        Remove the outlier
- Real value, but too extreme -	Cap it (set max limit)
- It makes trend misleading	 - Remove or explain it in reports
- You must keep all values	- Mention clearly in your analysis

In [ ]:
q1 = final_df["Booking_Value"].quantile(0.25)
q2 = final_df["Booking_Value"].quantile(0.75)

IQR = q2 - q1

lower = q1 - 1.5 * IQR
upper = q2 + 1.5 * IQR

outliers = final_df[(final_df['Booking_Value'] < lower) | (final_df['Booking_Value'] > upper)]

In [ ]:
outliers

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
19,2024-07-12 14:44:00,14:44:00,CNR1591113431,Success,CID902781,eBike,Koramangala,Sarjapur Road,245.0,70.0,NO,NO,No,NO,2014,Cash,33,4,4
28,2024-07-30 19:44:00,19:44:00,CNR6805579107,Success,CID810214,Prime SUV,Indiranagar,Indiranagar,35.0,145.0,NO,NO,No,NO,2183,Cash,20,4,4
49,2024-07-26 13:20:00,13:20:00,CNR9312632867,Success,CID649563,Prime SUV,Tumkur Road,Mysore Road,217.0,120.0,NO,NO,Yes,Vehicle Breakdown,2936,Cash,34,4,4
64,2024-07-04 15:32:00,15:32:00,CNR2735636504,Driver Not Found,CID111173,Prime SUV,Cox Town,Chamarajpet,0.0,0.0,NO,NO,NAN,NO,1310,NO,0,0,0
78,2024-07-29 14:56:00,14:56:00,CNR4314026109,Success,CID259573,Prime SUV,Tumkur Road,Bannerghatta Road,266.0,115.0,NO,NO,No,NO,2208,Cash,40,4,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20388,2024-07-22 23:46:00,23:46:00,CNR2092987062,Driver Not Found,CID441346,Prime Sedan,Hebbal,Shantinagar,0.0,0.0,NO,NO,NAN,NO,1521,NO,0,0,0
20392,2024-07-02 19:01:00,19:01:00,CNR1136510233,Success,CID828925,Bike,Yelahanka,Devanahalli,217.0,60.0,NO,NO,No,NO,1661,UPI,44,4,4
20395,2024-07-29 04:14:00,04:14:00,CNR5886368174,Driver Not Found,CID921441,Prime Plus,Magadi Road,Kammanahalli,0.0,0.0,NO,NO,NAN,NO,1690,NO,0,0,0
20398,2024-07-13 18:00:00,18:00:00,CNR6649153307,Success,CID231191,Prime SUV,Rajajinagar,Devanahalli,119.0,120.0,NO,NO,No,NO,1653,Cash,40,3,4
20404,2024-07-25 12:38:00,12:38:00,CNR2768163393,Success,CID214557,eBike,Electronic City,MG Road,210.0,105.0,NO,NO,No,NO,2184,Cash,21,3,3

In [ ]:
outliers.shape

(10116, 19)

In [ ]:
outliers.head(10)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
19,2024-07-12 14:44:00,14:44:00,CNR1591113431,Success,CID902781,eBike,Koramangala,Sarjapur Road,245.0,70.0,NO,NO,No,NO,2014,Cash,33,4,4
28,2024-07-30 19:44:00,19:44:00,CNR6805579107,Success,CID810214,Prime SUV,Indiranagar,Indiranagar,35.0,145.0,NO,NO,No,NO,2183,Cash,20,4,4
49,2024-07-26 13:20:00,13:20:00,CNR9312632867,Success,CID649563,Prime SUV,Tumkur Road,Mysore Road,217.0,120.0,NO,NO,Yes,Vehicle Breakdown,2936,Cash,34,4,4
64,2024-07-04 15:32:00,15:32:00,CNR2735636504,Driver Not Found,CID111173,Prime SUV,Cox Town,Chamarajpet,0.0,0.0,NO,NO,NO,NO,1310,NO,0,0,0
78,2024-07-29 14:56:00,14:56:00,CNR4314026109,Success,CID259573,Prime SUV,Tumkur Road,Bannerghatta Road,266.0,115.0,NO,NO,No,NO,2208,Cash,40,4,4
79,2024-07-17 19:55:00,19:55:00,CNR9027465661,Success,CID737388,Prime Sedan,BTM Layout,Majestic,168.0,30.0,NO,NO,No,NO,1695,UPI,20,4,4
81,2024-07-08 09:18:00,09:18:00,CNR2064658821,Success,CID954441,Bike,Peenya,Devanahalli,63.0,105.0,NO,NO,No,NO,2271,Cash,37,3,4
87,2024-07-21 06:54:00,06:54:00,CNR8369601219,Canceled by Driver,CID581505,Prime SUV,Richmond Town,Jayanagar,0.0,0.0,NO,Customer related issue,NO,NO,1609,NO,0,0,0
88,2024-07-22 00:21:00,00:21:00,CNR8346388703,Canceled by Driver,CID680143,Mini,Magadi Road,BTM Layout,0.0,0.0,NO,Personal & Car related issue,NO,NO,1821,NO,0,0,0
90,2024-07-26 06:06:00,06:06:00,CNR5528764313,Success,CID808205,Prime SUV,Ramamurthy Nagar,Bannerghatta Road,308.0,145.0,NO,NO,No,NO,2125,UPI,6,3,4

# **Save dataset for Power BI Analysis**

In [ ]:
#savefile
final_df.to_excel("ramacar&bikeservices.xlsx", index=False )

# index=False	Tells Pandas not to write the row index (0, 1, 2,...) into the excel file.
# This keeps the file clean and suitable for analysis or sharing.

In [ ]:
#download_to_desktop
from google.colab import files
files.download("ramacar&bikeservices.xlsx")

# **Changes that we need to do , as per client requirements**

1 - Wants reduce cost

2 - Wants reduce unnessary expensive

3 - Get more sales or orders

4 - Thinking about reduce some vechile so which they can reduce which can not effect much more on their business

5 - Wants to know which time and date are perfect  

6 - Identifying fake bookings

7 - Cost vs profit optimazation

8 - High cancellation rate area

9 - Expansion of business they want open new office

10 - Wants give reward to loyal costumers

11 - Driver behaviour analysis
kw

In [ ]:
final_df.head(1000)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NO,Personal & Car related issue,NAN,NO,444,NO,0,0,0
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NO,NO,No,NO,158,Cash,13,4,4
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NO,NO,No,NO,386,UPI,40,4,4
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NO,NAN,NO,384,NO,0,0,0
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NO,NO,No,NO,822,Credit Card,45,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2024-07-30 08:56:00,08:56:00,CNR1440190398,Canceled by Customer,CID436595,Auto,Peenya,Whitefield,0.0,0.0,Driver is not moving towards pickup location,NO,NAN,NO,599,NO,0,0,0
996,2024-07-15 01:40:00,01:40:00,CNR2463579135,Driver Not Found,CID493481,Bike,Vijayanagar,Marathahalli,0.0,0.0,NO,NO,NAN,NO,142,NO,0,0,0
997,2024-07-18 11:18:00,11:18:00,CNR3005238846,Canceled by Customer,CID906587,Bike,Tumkur Road,Vijayanagar,0.0,0.0,AC is Not working,NO,NAN,NO,688,NO,0,0,0
998,2024-07-29 03:11:00,03:11:00,CNR3639188731,Success,CID640076,Auto,Marathahalli,Shivajinagar,231.0,135.0,NO,NO,No,NO,290,Credit Card,18,4,4
999,2024-07-03 22:12:00,22:12:00,CNR2618079867,Canceled by Customer,CID993822,Prime Sedan,Shantinagar,Chickpet,0.0,0.0,Change of plans,NO,NAN,NO,419,NO,0,0,0

In [ ]:
final_df.Canceled_Rides_by_Customer.value_counts()

Canceled_Rides_by_Customer
NO                                              110851
Driver is not moving towards pickup location      3785
Driver asked to cancel                            3222
Change of plans                                   2489
AC is Not working                                 1888
Wrong Address                                     1196
Name: count, dtype: int64


# **1 Reduce Cost**

In [ ]:
#1-REDUCE COST

 #FIRE DRIVER WHICH HAS BAD PERFORMANCE (FINDING BAD PERFORMANCE FROM FOLLOWING WAY )

 # We don,t have driver_id directly because of that, we can not indentify driver directly , we do it throw vehicle type , e.g which driver
 # drive this vehicle maximun time , we would suggest next time keep driver it also

 # 1 (Which vehicle cancelled most ride by own , and not reached timely on location )


# Filter rows where Canceled_Rides_by_Customer is 'Driver is not moving towards pickup location & Driver asked to cancel '
# here we can not use group by because more that 1 condition

filtered = final_df[final_df['Canceled_Rides_by_Customer'].isin(['Driver is not moving towards pickup location','Driver asked to cancel'])]

# Count how many entries in 'Vehicle_Type' column meet that condition ( filtered)

vehiclewhichcanclledmostride1 = filtered['Vehicle_Type'].value_counts()

print(vehiclewhichcanclledmostride1)


#EBIKE & Auto drivers are maximum time cancel ride by own and not reach timely on location

Vehicle_Type
eBike          1027
Auto           1016
Prime SUV      1003
Bike           1002
Mini            997
Prime Plus      990
Prime Sedan     972
Name: count, dtype: int64

In [ ]:
#find the vehicle which cancel most ride because of "personal & car related issue here goup by because single parametere in condition

incomplte_rides_yes = final_df[final_df['Incomplete_Rides'].isin( ['Yes'] )]

vehiclewhichcanclledmostride2 = incomplte_rides_yes['Vehicle_Type'].value_counts()

print(vehiclewhichcanclledmostride2)

#Prime Sedan , Bike , eBike has maximun number of incomplete ride

Vehicle_Type
Prime Sedan    736
Bike           712
eBike          704
Prime SUV      669
Auto           655
Prime Plus     634
Mini           611
Name: count, dtype: int64

In [ ]:
#which vechile has less coustomer rating less than min(customer_rating)

Min_Vehicle_Rating = final_df['Customer_Rating'].mean()
print(Min_Vehicle_Rating)

2.2015620063031167

In [ ]:
final_df["Customer_Rating"].describe() #takes double confirmation

count    123431.000000
mean          2.201562
std           1.773508
min           0.000000
25%           0.000000
50%           3.000000
75%           4.000000
max           5.000000
Name: Customer_Rating, dtype: float64

In [ ]:
Minimum_Vechile_Rating = final_df[final_df['Customer_Rating'] <=(Min_Vehicle_Rating)]

In [ ]:
vehiclewhichcanclledmostride3 = Minimum_Vechile_Rating['Vehicle_Type'].value_counts()
print(vehiclewhichcanclledmostride3)

#Prime SUV & Ebike has less than mean(Customer_Ratings)

Vehicle_Type
Prime SUV      6820
eBike          6765
Prime Plus     6740
Auto           6691
Bike           6623
Prime Sedan    6591
Mini           6582
Name: count, dtype: int64

In [ ]:
#final output for cost reduction

print(vehiclewhichcanclledmostride1) #EBIKE & Auto drivers are maximum time cancel ride by own and not reach timely on location (you can fire them)

print(vehiclewhichcanclledmostride2) #Prime Sedan , Bike , eBike has most number of incomplete ride ( you can fire there drivers and reduce cost)

print(vehiclewhichcanclledmostride3) #Prime SUV & Ebike has less than mean['Customer_Ratings'] ( you can replace that bike also fire thier drivers)

#tip - Ebike in all 3 parameter costumers also don,t like and their drivers also look like careless

Vehicle_Type
eBike          1027
Auto           1016
Prime SUV      1003
Bike           1002
Mini            997
Prime Plus      990
Prime Sedan     972
Name: count, dtype: int64
Vehicle_Type
Prime Sedan    736
Bike           712
eBike          704
Prime SUV      669
Auto           655
Prime Plus     634
Mini           611
Name: count, dtype: int64
Vehicle_Type
Prime SUV      6820
eBike          6765
Prime Plus     6740
Auto           6691
Bike           6623
Prime Sedan    6591
Mini           6582
Name: count, dtype: int64

## **Unnessary Expense**

In [ ]:
#there no data present for finding your expense and unnessary expense we only have your pnl data there no columns or data for finding you unnessary expense
# here we can give you some more cost cutting idea which not giving to to much income it can be your unnessary income

### **Improve sales & get more orders**

In [ ]:
#geting location from where we get maximun number of orders

#count number of order per location

number_ofordervia_location = final_df['Pickup_Location'].value_counts()

print(number_ofordervia_location)

Pickup_Location
Banashankari            2639
RT Nagar                2568
Indiranagar             2550
Sahakar Nagar           2536
Tumkur Road             2535
Ramamurthy Nagar        2533
Magadi Road             2529
Basavanagudi            2525
Vijayanagar             2524
Cox Town                2522
Yeshwanthpur            2521
Kengeri                 2516
Sarjapur Road           2515
Mysore Road             2510
Kammanahalli            2509
Peenya                  2506
BTM Layout              2504
Nagarbhavi              2502
KR Puram                2500
Whitefield              2487
Langford Town           2483
Hennur                  2476
JP Nagar                2473
Malleshwaram            2473
Hosur Road              2470
Majestic                2467
Electronic City         2464
Bannerghatta Road       2453
Koramangala             2449
Yelahanka               2447
HSR Layout              2443
Frazer Town             2441
Rajarajeshwari Nagar    2435
Hebbal                  2433
Marathahalli            2433
Richmond Town           2431
Ulsoor                  2429
MG Road                 2424
Shantinagar             2423
Shivajinagar            2415
Chickpet                2410
Varthur                 2407
Bellandur               2405
Hulimavu                2404
Devanahalli             2402
Jayanagar               2402
Kadugodi                2397
Padmanabhanagar         2390
Chamarajpet             2384
Rajajinagar             2337
Name: count, dtype: int64

In [ ]:
# we get maximun order for which location

number_oforderfor_location = final_df["Drop_Location"].value_counts()
print(number_oforderfor_location)

Drop_Location
Peenya                  2587
Mysore Road             2577
HSR Layout              2560
MG Road                 2542
Marathahalli            2536
Sarjapur Road           2535
Hennur                  2534
Koramangala             2527
BTM Layout              2526
Vijayanagar             2524
Majestic                2523
Kengeri                 2520
Bannerghatta Road       2513
RT Nagar                2510
Kadugodi                2507
JP Nagar                2506
Hebbal                  2504
Sahakar Nagar           2501
Shivajinagar            2490
Tumkur Road             2487
Langford Town           2481
Hosur Road              2480
Jayanagar               2477
Malleshwaram            2469
Kammanahalli            2469
Banashankari            2466
Frazer Town             2464
Rajajinagar             2463
Shantinagar             2462
KR Puram                2452
Magadi Road             2450
Basavanagudi            2443
Yeshwanthpur            2442
Chickpet                2438
Devanahalli             2438
Padmanabhanagar         2437
Hulimavu                2434
Rajarajeshwari Nagar    2428
Electronic City         2423
Chamarajpet             2419
Ulsoor                  2416
Nagarbhavi              2416
Bellandur               2409
Richmond Town           2408
Indiranagar             2392
Varthur                 2391
Cox Town                2386
Ramamurthy Nagar        2381
Yelahanka               2374
Whitefield              2313
tT                         1
Name: count, dtype: int64

In [ ]:
# costomer will perfer which vechile most

fav_vechileof_costumer = final_df['Vehicle_Type'].value_counts()
print(fav_vechileof_costumer)

Vehicle_Type
Prime Sedan    17822
eBike          17813
Auto           17671
Bike           17611
Prime SUV      17600
Prime Plus     17495
Mini           17419
Name: count, dtype: int64

In [ ]:
# finding loyal costumer which book maximum success ride ( want to reward them )

#Filter for successful (completed) bookings
succesfull_bookings = final_df['Booking_Status'] == "Success"

# Group by Customer_ID and count successful rides
loyal_customers = (
    succesfull_bookings.groupby(final_df['Customer_ID'])
    .size()
    .reset_index(name='Successful_Rides')
    .sort_values(by='Successful_Rides', ascending=False)
)

loyal_customers.head(3)

      Customer_ID  Successful_Rides
89695   CID954071                 7
24062   CID329193                 6
19669   CID288207                 6

In [49]:
#finding the vechicle which generate maximun revune

#group by booking value by vechicle type
mostrrvaune_genratedvecicle = final_df.groupby('Vehicle_Type')['Booking_Value'].sum().sort_values(ascending=False)
print(mostrrvaune_genratedvecicle)

Vehicle_Type
Prime Sedan    9963861
eBike          9799880
Auto           9678687
Prime Plus     9594458
Bike           9570993
Mini           9564614
Prime SUV      9510792
Name: Booking_Value, dtype: int64

In [40]:
#which time we get maximum order '

final_df['Time'] = pd.to_datetime(final_df['Time'], format='%H:%M:%S', errors='coerce')

#Check how many still failed:
print("Unparsed rows:", final_df['Time'].isna().sum())

#Change datatype innto datetime format
final_df['Time'] = pd.to_datetime(final_df['Time'], errors='coerce')

#exact all hours from time (dt.hour geting us hour data )
final_df['Hour'] = final_df['Time'].dt.hour

#count number of order by per hours
number_oforder_perhour = final_df['Hour'].value_counts().sort_index()
print(number_oforder_perhour)

#Find the peak hour
peak_hour = number_oforder_perhour.idxmax()
peak_orders = number_oforder_perhour.max()
mostorder = (f"Most orders came at {peak_hour}:00 with {peak_orders} orders.")

Unparsed rows: 0
Hour
0     5163
1     5168
2     5134
3     5063
4     5127
5     5064
6     5131
7     5171
8     5267
9     5221
10    5240
11    5131
12    5254
13    5142
14    5045
15    5231
16    5085
17    5201
18    5031
19    5101
20    5066
21    5190
22    5127
23    5078
Name: count, dtype: int64

In [81]:
#high cancellation rate area

canceled_status = final_df['Booking_Status'].isin(['Canceled by Driver', 'Canceled by Customer'])

cancellation_counts = final_df[canceled_status].groupby(['Booking_ID' ,'Pickup_Location']).size().reset_index(name='Cancel_Counts')
print(cancellation_counts)

cancellation_counts.sort_values(by='Cancel_Counts', ascending=False)

          Booking_ID    Pickup_Location  Cancel_Counts
0      CNR1000057875           RT Nagar              1
1      CNR1000739586       Malleshwaram              1
2      CNR1001001397        Devanahalli              1
3      CNR1001007967       Banashankari              2
4      CNR1001021163         HSR Layout              1
...              ...                ...            ...
28928  CNR9999003386   Ramamurthy Nagar              1
28929  CNR9999039116           Chickpet              1
28930  CNR9999617236  Bannerghatta Road              1
28931  CNR9999692997        Rajajinagar              1
28932  CNR9999714482        Vijayanagar              1

[28933 rows x 3 columns]

          Booking_ID  Pickup_Location  Cancel_Counts
22395  CNR7987575311      Indiranagar              2
8120   CNR3526545870     Marathahalli              2
8110   CNR3523400750      Tumkur Road              2
22409  CNR7992768738         Majestic              2
8099   CNR3520491959       BTM Layout              2
...              ...              ...            ...
10648  CNR4307466923      Koramangala              1
10647  CNR4307444738       HSR Layout              1
10646  CNR4306947037        Yelahanka              1
10645  CNR4306920518       BTM Layout              1
10661  CNR4311109246  Padmanabhanagar              1

[28933 rows x 3 columns]

In [59]:
final_df.head(10)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Hour
0,2024-07-26 14:00:00,1900-01-01 14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,0.0,0.0,NO,Personal & Car related issue,NAN,NO,444,NO,0,0,0,14
1,2024-07-25 22:20:00,1900-01-01 22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NO,NO,No,NO,158,Cash,13,4,4,22
2,2024-07-30 19:59:00,1900-01-01 19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NO,NO,No,NO,386,UPI,40,4,4,19
3,2024-07-22 03:15:00,1900-01-01 03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,0.0,0.0,Driver is not moving towards pickup location,NO,NAN,NO,384,NO,0,0,0,3
4,2024-07-02 09:02:00,1900-01-01 09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NO,NO,No,NO,822,Credit Card,45,4,3,9
5,2024-07-13 04:42:00,1900-01-01 04:42:00,CNR8787177882,Success,CID802429,Mini,Kadugodi,Vijayanagar,231.0,90.0,NO,NO,No,NO,173,UPI,41,3,4,4
6,2024-07-23 09:51:00,1900-01-01 09:51:00,CNR3612067560,Success,CID476071,Bike,Tumkur Road,Whitefield,133.0,40.0,NO,NO,No,NO,140,Cash,49,3,4,9
7,2024-07-11 11:12:00,1900-01-01 11:12:00,CNR5374902489,Canceled by Driver,CID735691,Prime Plus,Bannerghatta Road,Sarjapur Road,0.0,0.0,NO,Personal & Car related issue,NAN,NO,344,NO,0,0,0,11
8,2024-07-01 19:19:00,1900-01-01 19:19:00,CNR5030602354,Driver Not Found,CID999840,Mini,Chamarajpet,Peenya,0.0,0.0,NO,NO,NAN,NO,839,NO,0,0,0,19
9,2024-07-18 01:31:00,1900-01-01 01:31:00,CNR6328453219,Canceled by Driver,CID907133,Auto,RT Nagar,Varthur,0.0,0.0,NO,Personal & Car related issue,NAN,NO,893,NO,0,0,0,1

In [82]:
#FINAL OUTPUT FOR GETTING MAXIMUN NUMBER OF ORDER FROM WHICH LOCATION

number_ofordervia_location.head(3) # we get maximun order from ( Banashankari , RT Nagar , Indiranagar )

number_oforderfor_location.head(3) # we get maximun order for ( Peenya , Mysore Road , HSR Layout )

fav_vechileof_costumer.head(3) # fav vechcle of costumer is ( prime sedan , ebike , auto )

loyal_customers.head(3) # loyal Customer names are following ( CID954071 , CID329193	, CID288207 )

print(mostorder)   #Most orders came at 8:00 with 5267 orders.

print(mostrrvaune_genratedvecicle) # Prime Sedan generated maximun revune for us

print(cancellation_counts) #high order cancellation form following areas ( Indiranagar	, Marathahalli , Tumkur Road )

          Booking_ID    Pickup_Location  Cancel_Counts
0      CNR1000057875           RT Nagar              1
1      CNR1000739586       Malleshwaram              1
2      CNR1001001397        Devanahalli              1
3      CNR1001007967       Banashankari              2
4      CNR1001021163         HSR Layout              1
...              ...                ...            ...
28928  CNR9999003386   Ramamurthy Nagar              1
28929  CNR9999039116           Chickpet              1
28930  CNR9999617236  Bannerghatta Road              1
28931  CNR9999692997        Rajajinagar              1
28932  CNR9999714482        Vijayanagar              1

[28933 rows x 3 columns]